#define __STDC__ 1
#define __STDC_VERSION__ 199901L
#define __STDC_HOSTED__ 1
#define __STDC_ISO_10646__ 200607
#define __EDG__ 1
#define __EDG_VERSION__ 407
#define __EDG_SIZE_TYPE__ unsigned int
#define __EDG_PTRDIFF_TYPE__ int
#define __sizeof_int 4
#define __sizeof_long 4
#define __sizeof_ptr 4
#define __ARMCC_VERSION 5060422
#define __TARGET_CPU_CORTEX_M4_FP 1
#define __TARGET_FPU_VFPV4_SP_D16 1
#define __MICROLIB 1
#define __UVISION_VERSION 523
#define _RTE_ 1
#define NRF52 1
#define NRF52832_XXAA 1
#define BLE_STACK_SUPPORT_REQD 1
#define BOARD_PCA10040 1
#define CONFIG_NFCT_PINS_AS_GPIOS 1
#define CONFIG_GPIO_AS_PINRESET 1
#define FREERTOS 1
#define NRF52_PAN_12 1
#define NRF52_PAN_15 1
#define NRF52_PAN_20 1
#define NRF52_PAN_31 1
#define NRF52_PAN_36 1
#define NRF52_PAN_51 1
#define NRF52_PAN_54 1
#define NRF52_PAN_55 1
#define NRF52_PAN_58 1
#define NRF52_PAN_64 1
#define NRF52_PAN_74 1
#define NRF_SD_BLE_API_VERSION 4
#define S132 1
#define SOFTDEVICE_PRESENT 1
#define __HEAP_SIZE 2048
#define __STACK_SIZE 4096
#define NRF_LOG_ENABLED 1
#define NRF_LOG_USES_RTT 1
#define PAVLOK_CFG_ENABLED 1
#define PAVLOK_SOL_ENABLED 1
#define PAVLOK_NOTIFY_ENABLED 1
#define PAVLOK_TRAIN_ENABLED 1
#define PAVLOK_APPSVC_ENABLED 1
#define PAVLOK_LOG_ENABLED 1
#define INCLUDE_SVC_TASK 1
#define INCLUDE_APP_TASK 1
#define INCLUDE_HABIT_TASK 1
#define INCLUDE_LOGGER_TASK 1
#define __CC_ARM 1
#define __arm 1
#define __arm__ 1
#define __TARGET_ARCH_7E_M 1
#define __TARGET_ARCH_ARM 0
#define __TARGET_ARCH_THUMB 4
#define __TARGET_ARCH_A64 0
#define __TARGET_ARCH_AARCH32 1
#define __TARGET_PROFILE_M 1
#define __TARGET_FEATURE_HALFWORD 1
#define __TARGET_FEATURE_THUMB 1
#define __TARGET_FEATURE_MULTIPLY 1
#define __TARGET_FEATURE_DSPMUL 1
#define __TARGET_FEATURE_DOUBLEWORD 1
#define __TARGET_FEATURE_DIVIDE 1
#define __TARGET_FEATURE_UNALIGNED 1
#define __TARGET_FEATURE_CLZ 1
#define __TARGET_FEATURE_DMB 1
#define __TARGET_FPU_VFPV4 1
#define __TARGET_FPU_VFP 1
#define __TARGET_FPU_VFP_SINGLE 1
#define __TARGET_FEATURE_EXTENSION_REGISTER_COUNT 16
#define __APCS_INTERWORK 1
#define __FP_FAST_FMAF 1
#define __thumb 1
#define __thumb__ 1
#define __t32__ 1
#define __OPTIMISE_SPACE 1
#define __OPTIMISE_LEVEL 0
